### ISSUE TITLE
Wiki Feedback

### ISSUE THREAD

**Issue by niartenyaw** [mingzhaogu/holler#1]
# Design Docs Feedback

Great job!! Just a few comments. Remember that you must have the wiki
complete before you'll be allowed to start coding tomorrow!

## MVP List

- [x] looks great!

### Wireframes

- [x] Make sure to label components!

### Component Hierarchy

- [x] Which of these components will need containers? What information
  from state will they need?

## State Shape

- [x] Nice! You'll probably also need a `conversations` slice of state to
  know who's in what conversation!

### Frontend

- [x] `/conversations/:conversationId` seems like a better choice, it
  makes it easier to generalize for both direct and group messaging!
- [x] Will logging in auto-select the most recent conversation?

### API Endpoints

- [x] Don't forget your `api/session` routes!
- [x] `POST /api/conversation/new`: typically POSTs are only to
  `POST /api/conversations`
- [x] How do you plan on saving messages?
- [x] Are you going to send all of the conversation info at once? Or will
  you only grab the messages for a particular conversation when it's
  selected?

## Schema

- [x] `is the Friendship Table necessary? should that be left as a bonus?`
 You can leave that as a bonus for now!

**Comment by niartenyaw** [comment]
You can fill in the checkboxes in my comment as well! I'll be taking a look over everything with you tomorrow. Thanks!!

**Comment by mingzhaogu** [comment]
I just updated my hierarchy with containers.
- [Component Hierarchy](https://github.com/mingzhaogu/holler/wiki/Component-Hierarchy)
- [Wireframes](https://github.com/mingzhaogu/holler/wiki/Wireframes)

Please let me know if there's anything else I should add.

Thanks!
