### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by mingzhaogu** [mingzhaogu/holler#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by mingzhaogu** [comment]
[Holler Link](https://holler-messenger.herokuapp.com/#/)

**Comment by mingzhaogu** [comment]
Question: For demo login, I created a button that calls login({hardcoded user details}) onClick. when I log in and open console, I see this error:

> Failed to load resource: the server responded with a status of 401 (Unauthorized)

Am I doing something incorrectly?

**Comment by niartenyaw** [comment]
Nice!! Looks great!

## Functionality

- [ ] Incorrect form entries needs to render the errors to the user!

## Styling

- [ ] `Sign In` and `Demo` button should match Messenger's button
- [ ] There should be an image to the right of the form like Messenger. You can just have the image on both `/login` and `/signup`, don't worry about taking the image off for the other two pages like Messenger does.

**Comment by niartenyaw** [comment]
And for the error, I don't think that's a problem with the demo user. I feel like that's an asset (probably an image) problem

**Comment by niartenyaw** [comment]
Looks amazing! Two more quick things and then feel free to mark this as complete!

## Functionality

- [ ] When moving between `/signup` and `/login`, the errors should clear

## Styling

- [ ] When I hover the buttons, I should get the `pointer` cursor
